server:
  port: 8080

spring:
  application:
    name: toDoList

#  datasource:
#    url: jdbc:mysql://localhost:3306/toDolistDB?useSSL=false
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:sqlite:./todoListDB
    driver-class-name: org.sqlite.JDBC


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.community.dialect.SQLiteDialect



jwt:
  secret: ${JWT_SECRET}
  expirationMs: 3600000  # 1 hour
  issuer: "https://api.todolist.com"
  audience: "todo-api"

